### ISSUE TITLE
Add prettier peer dependency

### ISSUE THREAD

**Issue by jaronheard** [Acidic9/prettier-plugin-tailwind#10]
Since Prettier is [recommended to be installed/used as an exact version](https://prettier.io/docs/en/install.html), the lowest compatible version you support should be specified as a peer dependency. You may also want to specify this in the docs.

Here's an example of an active official plugin that uses this pattern:
https://github.com/prettier/plugin-pug/blob/master/package.json

Here's what I tested:
1.16.4 -- not working
1.19.1 -- working
2.0.0 -- working
2.2.0 -- working

Here's the error that I get with 1.16.4 in VSCode. It looks like at that time plugin support was still experimental.
```
["ERROR" - 10:02:55 PM] Error formatting document.
["ERROR" - 10:02:55 PM] Unexpected type string
Error: Unexpected type string
	at optionInfoToSchema (/Users/jaronheard/temp/civic/node_modules/prettier/index.js:8872:13)
	at optionInfosToSchemas (/Users/jaronheard/temp/civic/node_modules/prettier/index.js:8789:20)
	at normalizeOptions$1 (/Users/jaronheard/temp/civic/node_modules/prettier/index.js:8749:17)
	at Object.normalizeApiOptions (/Users/jaronheard/temp/civic/node_modules/prettier/index.js:8921:10)
	at normalize (/Users/jaronheard/temp/civic/node_modules/prettier/index.js:10732:28)
	at formatWithCursor (/Users/jaronheard/temp/civic/node_modules/prettier/index.js:14130:12)
	at /Users/jaronheard/temp/civic/node_modules/prettier/index.js:42399:15
	at Object.format (/Users/jaronheard/temp/civic/node_modules/prettier/index.js:42418:12)
	at t.default.<anonymous> (/Users/jaronheard/.vscode/extensions/esbenp.prettier-vscode-5.8.0/dist/extension.js:1:17599)
	at Generator.next (<anonymous>)
	at s (/Users/jaronheard/.vscode/extensions/esbenp.prettier-vscode-5.8.0/dist/extension.js:1:11597)
```

This error also occurs running the CLI, and occurs regardless of whether the `twPluginsOrder` is specified in the `.prettierrc` file.

Thanks for your work on this, it's very cool 😎

**Comment by Acidic9** [comment]
Wow, thanks so much.. it looks like you already did all the hard work for me. Much appreciated, I'll add prettier as a peer dependency later today!

**Comment by Acidic9** [comment]
Added prettier `^2.0.0` as peer dependency with release 2.2.1 of `prettier-plugin-tailwind`. Thanks for opening this issue!
