### ISSUE TITLE
Error: Cannot find module 'svelte-prettier-plugin'

### ISSUE THREAD

**Issue by benknight** [Acidic9/prettier-plugin-tailwind#13]
I've just installed this plugin using `npm install --save-dev prettier-plugin-tailwind`. I'm not using Svelte at all but when I run prettier I get the following error:

```
▶ npm run format

> vietnamcoracle-next@ format /Users/ben/Code/vietnamcoracle-next
> prettier --write "src/**/*.{js,jsx}"

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'svelte-prettier-plugin'
Require stack:
- /Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/lib/languages/svelte.js
- /Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/lib/languages/index.js
- /Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/lib/index.js
- /Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/prettier-plugin-tailwind.js
- /Users/ben/Code/vietnamcoracle-next/node_modules/prettier/index.js
- /Users/ben/Code/vietnamcoracle-next/node_modules/prettier/bin-prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/lib/languages/svelte.js:3:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/lib/languages/svelte.js',
    '/Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/lib/languages/index.js',
    '/Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/lib/index.js',
    '/Users/ben/Code/vietnamcoracle-next/node_modules/prettier-plugin-tailwind/prettier-plugin-tailwind.js',
    '/Users/ben/Code/vietnamcoracle-next/node_modules/prettier/index.js',
    '/Users/ben/Code/vietnamcoracle-next/node_modules/prettier/bin-prettier.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vietnamcoracle-next@ format: `prettier --write "src/**/*.{js,jsx}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vietnamcoracle-next@ format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ben/.npm/_logs/2020-12-03T03_04_06_288Z-debug.log
```

**Comment by benknight** [comment]
Downgrading to v2.1.9 solved the issue for me.

**Comment by Acidic9** [comment]
@benknight I tried using npm and yarn to format but haven't been able to reproduce this error.

If it still persists, perhaps opening a reproduction repo will help.

**Comment by Acidic9** [comment]
@benknight it would be helpful if you could provide the version of NPM/Yarn you are using and the version of prettier.

**Comment by kripod** [comment]
I just encountered the same issue using npm v6.14.8 and Prettier v2.2.1. Neither `svelte-prettier-plugin` or `prettier-plugin-svelte` can be found in my `package-lock.json` file.

**Comment by mryechkin** [comment]
Looks like I was having this issue as well, was getting the `Prettier cannot format [file].js` error - looking for solutions led me to this issue.

Downgrading to `2.1.9` as @benknight suggested worked for me 👍

**Comment by Acidic9** [comment]
In `v2.2.8` I've removed svelte support. I'm not sure on how to fix this so for now I've just removed the issue and it should be working again now.
